Fix cerebro.plot() in jupyter
mementum/backtrader pull request #423
Opened 2020-08-16 21:12 UTC by adrianocavalari

.plot is not displaying the graph

2020-10-10 00:46 UTC, adrianocavalari commented
Forgot to check when in py file, now both working

2021-01-14 13:59 UTC, calpa commented
When will this PR be merged?

2021-02-22 19:09 UTC, vladisld requested changes

2021-02-22 19:09 UTC, vladisld commented on backtrader/plot/plot.py
> +        from IPython import get_ipython
IPython is not the prerequisite for the backtrader ( as matplotlib - see https://www.backtrader.com/docu/installation/).

So importing the `get_ipython` method may fail - please put this code inside the try..except.

2022-06-19 22:56 UTC, closed without merging